#!/usr/bin/env python3
"""
SATA Preferred Equity Valuation Model

This script values SATA preferred stock by discounting future dividends, where dividends
are funded by Bitcoin sales after cash reserves are depleted. Bitcoin price paths are
loaded from files generated by btc_price_paths.py.

The script performs:
1. Baseline scenario dividend sustainability analysis
2. Multi-scenario NPV analysis (across different Bitcoin starting prices)
3. Sensitivity analysis (dividend suspension threshold multiplier)
4. Generates an HTML report with embedded charts and tables
"""

# Standard library imports
import argparse
import base64
import io
import json
import logging
import os
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path
from multiprocessing import cpu_count
from typing import Dict, List, Optional, Tuple, Any
from numba import jit
import gc  # For memory management

# Third-party imports
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

# Configure matplotlib for non-interactive use
matplotlib.use('Agg')

from strc_paths import OUTPUT_DIR as DEFAULT_OUTPUT_DIR, PLOTS_DIR as DEFAULT_PLOTS_DIR, REPORTS_DIR, ensure_output_dirs

# Suppress warnings for cleaner output
import warnings
warnings.filterwarnings('ignore')

# Set random seed for reproducibility
np.random.seed(42)

# ============================================================================
# CONFIGURATION MANAGEMENT
# ============================================================================

class Configuration:
    """Centralized configuration management for SATA valuation model."""

    def __init__(self,
                 # SATA Parameters
                 sata_shares_outstanding: int = 2012700,
                 sata_annual_dividend_rate: float = 0.1225,
                 sata_par_value: float = 100.0,

                 # Treasury Parameters
                 initial_bitcoin_holdings: float = 7525.02,
                 initial_cash_reserve: float = 67600000.0,  # Default: ~67M (will be overridden by treasury_extracted_data.json if available)

                 # Financial Parameters
                 discount_rate_annual: float = 0.04159,

                 # Dividend Parameters
                 dividend_suspension_threshold_multiplier: float = 1.25,
                 compounded_dividend_start_rate: float = 0.1250,
                 compounded_dividend_increment: float = 0.0025,
                 compounded_dividend_max_rate: float = 0.20,

                 # Sensitivity Analysis
                 sensitivity_threshold_start: float = 0.0,
                 sensitivity_threshold_end: float = 2.0,
                 sensitivity_threshold_step: float = 0.25,

                 # BTC Credit Sensitivity Analysis - parameters calculated dynamically from current BTC credit ratio

                 # Performance Parameters
                 default_num_workers: Optional[int] = None,
                 chunk_size_multiplier: int = 8,

                 # Override from external data
                 **overrides):
        """Initialize configuration with defaults and optional overrides."""

        # SATA Parameters
        self.sata_shares_outstanding = overrides.get('sata_shares', sata_shares_outstanding)
        self.sata_annual_dividend_rate = overrides.get('sata_dividend_rate', sata_annual_dividend_rate)
        self.sata_par_value = sata_par_value

        # Treasury Parameters
        self.initial_bitcoin_holdings = overrides.get('bitcoin_holdings', initial_bitcoin_holdings)
        self.initial_cash_reserve = overrides.get('cash', initial_cash_reserve)

        # Financial Parameters
        self.discount_rate_annual = discount_rate_annual

        # Dividend Parameters
        self.dividend_suspension_threshold_multiplier = dividend_suspension_threshold_multiplier
        self.compounded_dividend_start_rate = compounded_dividend_start_rate
        self.compounded_dividend_increment = compounded_dividend_increment
        self.compounded_dividend_max_rate = compounded_dividend_max_rate

        # Sensitivity Analysis
        self.sensitivity_threshold_start = sensitivity_threshold_start
        self.sensitivity_threshold_end = sensitivity_threshold_end
        self.sensitivity_threshold_step = sensitivity_threshold_step

        # Dividend Rate Sensitivity Analysis
        self.dividend_rate_sensitivity_start_pct = -1.0   # -1.0% of baseline
        self.dividend_rate_sensitivity_end_pct = 1.0      # +1.0% of baseline
        self.dividend_rate_sensitivity_step_pct = 0.25    # 0.25% increments

        # BTC Credit Sensitivity Analysis - parameters calculated dynamically

        # Performance Parameters
        self.default_num_workers = default_num_workers
        self.chunk_size_multiplier = chunk_size_multiplier if chunk_size_multiplier is not None else 8
        self.enable_early_termination = True  # Enable early termination for insolvent simulations
        self.optimization_level = 2  # 0=baseline, 1=moderate, 2=aggressive optimizations

        # Computed properties
        self._computed_values = {}

    @property
    def sata_monthly_dividend_per_share(self) -> float:
        """Calculate monthly dividend per share."""
        return self.sata_annual_dividend_rate * self.sata_par_value / 12

    @property
    def sata_monthly_dividend_total(self) -> float:
        """Calculate total monthly dividend payment."""
        return self.sata_monthly_dividend_per_share * self.sata_shares_outstanding

    @property
    def total_par_value(self) -> float:
        """Calculate total par value of all shares."""
        return self.sata_shares_outstanding * self.sata_par_value

    @property
    def monthly_discount_rate(self) -> float:
        """Calculate monthly discount rate."""
        return (1 + self.discount_rate_annual) ** (1/12) - 1

    def get_sensitivity_thresholds(self) -> np.ndarray:
        """Get array of threshold multipliers for sensitivity analysis, excluding baseline."""
        all_thresholds = np.arange(self.sensitivity_threshold_start,
                                  self.sensitivity_threshold_end + self.sensitivity_threshold_step,
                                  self.sensitivity_threshold_step)
        # Exclude the baseline threshold multiplier to avoid redundant calculation
        return all_thresholds[np.abs(all_thresholds - self.dividend_suspension_threshold_multiplier) > 1e-6]

    def get_dividend_rate_sensitivity_values(self) -> np.ndarray:
        """Get array of dividend rates for dividend rate sensitivity analysis, excluding baseline."""
        start_rate = self.sata_annual_dividend_rate + (self.dividend_rate_sensitivity_start_pct / 100)
        end_rate = self.sata_annual_dividend_rate + (self.dividend_rate_sensitivity_end_pct / 100)
        step_rate = self.dividend_rate_sensitivity_step_pct / 100
        all_rates = np.arange(start_rate, end_rate + step_rate, step_rate)
        # Exclude the baseline dividend rate to avoid redundant calculation
        return all_rates[np.abs(all_rates - self.sata_annual_dividend_rate) > 1e-6]


    def to_dict(self) -> Dict[str, Any]:
        """Convert configuration to dictionary for worker functions."""
        return {
            'num_simulations': None,  # Set by price data
            'simulation_years': None,  # Set by price data
            'total_months': None,  # Set by price data
            'current_bitcoin_price': None,  # Set by price data
            'sata_shares_outstanding': self.sata_shares_outstanding,
            'sata_annual_dividend_rate': self.sata_annual_dividend_rate,
            'sata_par_value': self.sata_par_value,  # Add this line
            'sata_monthly_dividend_per_share': self.sata_monthly_dividend_per_share,
            'sata_monthly_dividend_total': self.sata_monthly_dividend_total,
            'initial_bitcoin_holdings': self.initial_bitcoin_holdings,
            'initial_cash_reserve': self.initial_cash_reserve,
            'total_par_value': self.total_par_value,
            'dividend_suspension_threshold_multiplier': self.dividend_suspension_threshold_multiplier,
            'compounded_dividend_start_rate': self.compounded_dividend_start_rate,
            'compounded_dividend_increment': self.compounded_dividend_increment,
            'compounded_dividend_max_rate': self.compounded_dividend_max_rate,
        'discount_rate_annual': self.discount_rate_annual,
        'monthly_discount_rate': self.monthly_discount_rate,
        'enable_early_termination': self.enable_early_termination
        }

    def validate(self) -> None:
        """Validate configuration parameters."""
        if self.sata_shares_outstanding <= 0:
            raise ValueError("SATA shares outstanding must be positive")
        if not (0 < self.sata_annual_dividend_rate <= 1):
            raise ValueError("SATA dividend rate must be between 0 and 1")
        if self.sata_par_value <= 0:
            raise ValueError("SATA par value must be positive")
        if self.initial_bitcoin_holdings < 0:
            raise ValueError("Initial Bitcoin holdings cannot be negative")
        if self.initial_cash_reserve < 0:
            raise ValueError("Initial cash reserve cannot be negative")
        if self.discount_rate_annual < 0:
            raise ValueError("Discount rate cannot be negative")
        if self.dividend_suspension_threshold_multiplier <= 0:
            raise ValueError("Dividend suspension threshold must be positive")

    def __str__(self) -> str:
        """String representation of configuration."""
        return f"""Configuration:
  SATA: {self.sata_shares_outstanding:,} shares @ ${self.sata_par_value:.0f} par ({self.sata_annual_dividend_rate:.2%} yield)
  Treasury: {self.initial_bitcoin_holdings:,.2f} BTC + ${self.initial_cash_reserve:,.0f} cash
  Finance: {self.discount_rate_annual:.2%} annual discount rate
  Suspension: {self.dividend_suspension_threshold_multiplier:.2f}x par value threshold"""

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================

def setup_logging(verbose: bool = True) -> logging.Logger:
    """Setup logging configuration."""
    logger = logging.getLogger('sata_valuation')
    logger.setLevel(logging.INFO if verbose else logging.WARNING)

    # Remove existing handlers to avoid duplicates
    for handler in logger.handlers[:]:
        logger.removeHandler(handler)

    # Create console handler
    handler = logging.StreamHandler()
    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    logger.addHandler(handler)

    return logger


# Global logger instance
logger = setup_logging()

# ============================================================================
# NUMBA OPTIMIZATIONS
# ============================================================================

@jit(nopython=True, parallel=False)
def calculate_npv_matrix_multiplication(cash_flows: np.ndarray, discount_factors: np.ndarray) -> float:
    """Calculate NPV using matrix multiplication with precomputed discount factors.

    Parameters:
    - cash_flows: Array of cash flows for each month (shape: n_months)
    - discount_factors: Precomputed discount factors for each month (shape: n_months)
                      where discount_factors[t] = (1 + r)^(t+1)

    Returns:
    - NPV value
    """
    return np.sum(cash_flows / discount_factors)


# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

def execute_parallel_with_fallback(worker_function: callable, tasks: List[Any],
                                 num_workers: int, description: str = "tasks") -> List[Any]:
    """Execute tasks in parallel with automatic fallback to sequential processing.

    Args:
        worker_function: Function to execute for each task
        tasks: List of task arguments
        num_workers: Number of worker processes to use
        description: Description for progress messages

    Returns:
        List of results from worker function
    """
    results = []

    try:
        with ProcessPoolExecutor(max_workers=num_workers) as executor:
            futures = {executor.submit(worker_function, task): task for task in tasks}
            for future in as_completed(futures):
                results.append(future.result())
                print(f"  Progress: {len(results)}/{len(tasks)} {description} completed...")

    except (OSError, PermissionError) as e:
        print(f"  Multiprocessing failed ({e}), falling back to sequential processing...")
        # Fallback to sequential processing
        for task in tasks:
            result = worker_function(task)
            results.append(result)
            print(f"  Progress: {len(results)}/{len(tasks)} {description} completed...")

    return results


# ============================================================================
# CONFIGURATION LOADING
# ============================================================================

def load_btcc_data(data_dir: Optional[str] = None) -> Dict[str, Any]:
    """Load treasury data from ``<data_dir>/treasury_extracted_data.json`` (from test_treasury_api.py)."""
    data: Dict[str, Any] = {}
    root = Path(data_dir) if data_dir else DEFAULT_OUTPUT_DIR
    treasury_data_file = root / "treasury_extracted_data.json"

    if not treasury_data_file.is_file():
        print("  Run: python test_treasury_api.py to fetch latest data.")
        return {}

    try:
        with open(treasury_data_file, 'r') as f:
            treasury_data = json.load(f)
        print(f"✓ Loaded treasury data from {treasury_data_file}")
        if 'timestamp' in treasury_data:
            print(f"  Data timestamp: {treasury_data['timestamp']}")

        if 'btc_holdings' in treasury_data:
            data['bitcoin_holdings'] = treasury_data['btc_holdings']
            print(f"  BTC Holdings: {data['bitcoin_holdings']:,.2f} BTC")

        if 'cash' in treasury_data:
            data['cash'] = treasury_data['cash']
            print(f"  Cash: ${data['cash']:,.0f}")

        if 'sata_shares' in treasury_data:
            data['sata_shares'] = treasury_data['sata_shares']
            print(f"  SATA Shares: {data['sata_shares']:,}")

        if 'sata_dividend_rate' in treasury_data:
            dividend_rate = treasury_data['sata_dividend_rate']
            if dividend_rate > 1:
                dividend_rate = dividend_rate / 100.0
            data['sata_dividend_rate'] = dividend_rate
            print(f"  SATA Dividend Rate: {data['sata_dividend_rate']:.2%}")

        if 'sata_price' in treasury_data:
            data['sata_current_price'] = treasury_data['sata_price']
            print(f"  SATA Current Price: ${data['sata_current_price']:.2f}")

        return data
    except Exception as e:
        print(f"⚠ Error loading {treasury_data_file}: {e}")
        return {}


def load_price_paths(data_dir: Optional[str] = None) -> Dict[str, Any]:
    """Load Bitcoin price paths from ``<data_dir>/`` (split npy/npz or JSON formats)."""
    root = Path(data_dir) if data_dir else DEFAULT_OUTPUT_DIR

    price_paths_file = str(root / "btc_price_paths_scenarios_price_paths.npy")
    metadata_file = str(root / "btc_price_paths_scenarios_metadata.npz")
    json_file_scenarios = str(root / "btc_price_paths_scenarios.json")
    json_file_old = str(root / "btc_price_paths.json")
    
    use_npz = False
    use_scenarios = False
    
    # Try split files first (fastest)
    if os.path.exists(price_paths_file) and os.path.exists(metadata_file):
        print(f"Loading Bitcoin price paths from split files (optimized format)...")
        print(f"  Price paths: {price_paths_file}")
        print(f"  Metadata: {metadata_file}")
        use_npz = True
        use_scenarios = True
        
        # Load metadata
        metadata_npz = np.load(metadata_file)
        num_simulations = int(metadata_npz['num_simulations'])
        simulation_years = int(metadata_npz['simulation_years'])
        total_months = int(metadata_npz['total_months'])
        current_bitcoin_price = float(metadata_npz['current_bitcoin_price'])
        num_scenarios = int(metadata_npz['num_scenarios'])
        
        distribution_params = {
            'mean': float(metadata_npz['distribution_mean']),
            'std': float(metadata_npz['distribution_std']),
            'skew': float(metadata_npz['distribution_skew']),
            'kurtosis': float(metadata_npz['distribution_kurtosis']),
            'tail_weight': float(metadata_npz['distribution_tail_weight']),
            'asymmetry': float(metadata_npz['distribution_asymmetry'])
        }
        
        starting_price_pcts = metadata_npz['starting_price_pcts']
        starting_prices = metadata_npz['starting_prices']
        metadata_npz.close()
        
        # Load price paths (uncompressed, fast) - memory map for large files
        file_size_gb = os.path.getsize(price_paths_file) / (1024**3)
        print(f"  Loading price paths array ({file_size_gb:.2f} GB)...")

        # Use memory mapping for large files to reduce memory pressure
        if file_size_gb > 1.0:  # Memory map files > 1GB
            all_price_paths = np.load(price_paths_file, mmap_mode='r')
        else:
            all_price_paths = np.load(price_paths_file)
        
        # Convert to list of scenario dictionaries for compatibility
        scenarios = []
        for i in range(num_scenarios):
            scenarios.append({
                'starting_price_pct': float(starting_price_pcts[i]),
                'starting_price': float(starting_prices[i]),
                'price_paths': all_price_paths[i].tolist()
            })
        
        print(f"✓ Successfully loaded {num_scenarios} scenarios from split files!")
        print(f"  Each scenario: {num_simulations:,} simulations")
        print(f"  Simulation period: {simulation_years} years ({total_months:,} months)")
        print(f"  Current Bitcoin price: ${current_bitcoin_price:,.2f}")
        
        return {
            'num_simulations': num_simulations,
            'simulation_years': simulation_years,
            'total_months': total_months,
            'current_bitcoin_price': current_bitcoin_price,
            'num_scenarios': num_scenarios,
            'scenarios': scenarios,
            'distribution_params': distribution_params
        }
    
    elif os.path.exists(json_file_scenarios):
        print(f"Loading Bitcoin price paths from {json_file_scenarios}...")
        with open(json_file_scenarios, 'r') as f:
            price_data = json.load(f)
        
        num_simulations = price_data['num_simulations']
        simulation_years = price_data['simulation_years']
        total_months = price_data['total_months']
        current_bitcoin_price = price_data.get('current_bitcoin_price', price_data.get('initial_price', 86817.19))
        num_scenarios = price_data.get('num_scenarios', 1)
        scenarios = price_data['scenarios']
        distribution_params = price_data['distribution_params']
        
        print(f"✓ Successfully loaded {num_scenarios} scenarios from JSON format!")
        print(f"  Each scenario: {num_simulations:,} simulations")
        print(f"  Simulation period: {simulation_years} years ({total_months:,} months)")
        print(f"  Current Bitcoin price: ${current_bitcoin_price:,.2f}")
        
        return {
            'num_simulations': num_simulations,
            'simulation_years': simulation_years,
            'total_months': total_months,
            'current_bitcoin_price': current_bitcoin_price,
            'num_scenarios': num_scenarios,
            'scenarios': scenarios,
            'distribution_params': distribution_params
        }
    
    elif os.path.exists(json_file_old):
        print(f"Loading Bitcoin price paths from {json_file_old}...")
        with open(json_file_old, 'r') as f:
            price_data = json.load(f)
        
        num_simulations = price_data['num_simulations']
        simulation_years = price_data['simulation_years']
        total_months = price_data['total_months']
        current_bitcoin_price = price_data.get('initial_price', price_data.get('current_bitcoin_price', 86817.19))
        num_scenarios = 1
        
        scenarios = [{
            'starting_price_pct': 0.0,
            'starting_price': current_bitcoin_price,
            'price_paths': price_data['price_paths']
        }]
        distribution_params = price_data['distribution_params']
        
        return {
            'num_simulations': num_simulations,
            'simulation_years': simulation_years,
            'total_months': total_months,
            'current_bitcoin_price': current_bitcoin_price,
            'num_scenarios': num_scenarios,
            'scenarios': scenarios,
            'distribution_params': distribution_params
        }
    
    else:
        raise FileNotFoundError(
            f"Error: None of the expected files found!\n"
            f"  Expected: {price_paths_file} and {metadata_file} (recommended), {json_file_scenarios}, or {json_file_old}\n"
            f"Please run btc_price_paths.py first to generate the price paths."
        )


# ============================================================================
# DATA STRUCTURES
# ============================================================================

class DividendSimulationResult:
    """Result of a single dividend simulation."""

    def __init__(self, sim_start: int, sim_end: int,
                 months_dividends_paid: np.ndarray,
                 final_bitcoin_holdings: np.ndarray,
                 final_cash_reserve: np.ndarray,
                 accumulated_unpaid_dividends_final: np.ndarray,
                 npvs: np.ndarray):
        self.sim_start = sim_start
        self.sim_end = sim_end
        self.months_dividends_paid = months_dividends_paid
        self.final_bitcoin_holdings = final_bitcoin_holdings
        self.final_cash_reserve = final_cash_reserve
        self.accumulated_unpaid_dividends_final = accumulated_unpaid_dividends_final
        self.npvs = npvs


# NPVCalculationResult removed - using structured arrays


# Unified result storage using structured numpy arrays for vectorized operations
RESULT_DTYPE = np.dtype([
    ('result_type', 'U20'),        # Analysis type identifier
    ('scenario_idx', 'i4'),        # Scenario index (scenarios only)
    ('starting_price_pct', 'f8'),  # Scenario: percentage change from baseline
    ('starting_price', 'f8'),      # Scenario: absolute starting price
    ('threshold_multiplier', 'f8'), # Threshold sensitivity: multiplier value
    ('threshold_value', 'f8'),     # Threshold sensitivity: absolute threshold value
    ('dividend_rate', 'f8'),       # Dividend rate sensitivity: rate value
    ('dividend_rate_change_pct', 'f8'), # Dividend rate sensitivity: percentage change
    ('btc_credit_ratio', 'f8'),    # BTC credit sensitivity: ratio value
    ('btc_holdings', 'f8'),        # BTC credit sensitivity: required holdings
    ('mean_npv_per_share', 'f8'),
    ('median_npv_per_share', 'f8'),
    ('mean_months_paid', 'f8'),
    ('mean_accumulated_unpaid', 'f8'),
    ('std_npv_per_share', 'f8'),
    ('min_npv_per_share', 'f8'),   # Scenarios only
    ('max_npv_per_share', 'f8'),   # Scenarios only
    ('npv_per_additional_btc', 'f8') # BTC credit elasticity
])

# Legacy result classes removed - using RESULT_DTYPE structured arrays exclusively

# Helper functions for creating structured array results
def create_scenario_result(scenario_idx: int, starting_price_pct: float, starting_price: float,
                          mean_npv_per_share: float, median_npv_per_share: float,
                          mean_months_paid: float, std_npv_per_share: float,
                          min_npv_per_share: float, max_npv_per_share: float) -> np.ndarray:
    """Create a single scenario result in structured array format."""
    result = np.zeros(1, dtype=RESULT_DTYPE)
    result['result_type'] = 'scenario'
    result['scenario_idx'] = scenario_idx
    result['starting_price_pct'] = starting_price_pct
    result['starting_price'] = starting_price
    result['mean_npv_per_share'] = mean_npv_per_share
    result['median_npv_per_share'] = median_npv_per_share
    result['mean_months_paid'] = mean_months_paid
    result['std_npv_per_share'] = std_npv_per_share
    result['min_npv_per_share'] = min_npv_per_share
    result['max_npv_per_share'] = max_npv_per_share
    return result

def create_sensitivity_threshold_result(threshold_multiplier: float, threshold_value: float,
                                       mean_npv_per_share: float, median_npv_per_share: float,
                                       mean_months_paid: float, mean_accumulated_unpaid: float,
                                       std_npv_per_share: float) -> np.ndarray:
    """Create a single threshold sensitivity result in structured array format."""
    result = np.zeros(1, dtype=RESULT_DTYPE)
    result['result_type'] = 'sensitivity_threshold'
    result['threshold_multiplier'] = threshold_multiplier
    result['threshold_value'] = threshold_value
    result['mean_npv_per_share'] = mean_npv_per_share
    result['median_npv_per_share'] = median_npv_per_share
    result['mean_months_paid'] = mean_months_paid
    result['mean_accumulated_unpaid'] = mean_accumulated_unpaid
    result['std_npv_per_share'] = std_npv_per_share
    return result

def create_sensitivity_dividend_rate_result(dividend_rate: float, dividend_rate_change_pct: float,
                                           mean_npv_per_share: float, median_npv_per_share: float,
                                           mean_months_paid: float, mean_accumulated_unpaid: float,
                                           std_npv_per_share: float) -> np.ndarray:
    """Create a single dividend rate sensitivity result in structured array format."""
    result = np.zeros(1, dtype=RESULT_DTYPE)
    result['result_type'] = 'sensitivity_dividend_rate'
    result['dividend_rate'] = dividend_rate
    result['dividend_rate_change_pct'] = dividend_rate_change_pct
    result['mean_npv_per_share'] = mean_npv_per_share
    result['median_npv_per_share'] = median_npv_per_share
    result['mean_months_paid'] = mean_months_paid
    result['mean_accumulated_unpaid'] = mean_accumulated_unpaid
    result['std_npv_per_share'] = std_npv_per_share
    return result

def create_sensitivity_btc_credit_result(btc_credit_ratio: float, btc_holdings: float,
                                        mean_npv_per_share: float, median_npv_per_share: float,
                                        mean_months_paid: float, mean_accumulated_unpaid: float,
                                        std_npv_per_share: float,
                                        npv_per_additional_btc: float = 0.0) -> np.ndarray:
    """Create a single BTC credit sensitivity result in structured array format."""
    result = np.zeros(1, dtype=RESULT_DTYPE)
    result['result_type'] = 'sensitivity_btc_credit'
    result['btc_credit_ratio'] = btc_credit_ratio
    result['btc_holdings'] = btc_holdings
    result['mean_npv_per_share'] = mean_npv_per_share
    result['median_npv_per_share'] = median_npv_per_share
    result['mean_months_paid'] = mean_months_paid
    result['mean_accumulated_unpaid'] = mean_accumulated_unpaid
    result['std_npv_per_share'] = std_npv_per_share
    result['npv_per_additional_btc'] = npv_per_additional_btc
    return result


class BaselineResults:
    """Results from baseline scenario analysis."""

    def __init__(self, final_valuation_per_share: float, final_valuation_total: float,
                 valuation_vs_par: float, mean_months_paid: float,
                 median_months_paid: float,
                 mean_accumulated_unpaid: float, mean_npv_per_share: float,
                 median_npv_per_share: float, std_npv_per_share: float,
                 cv_npv_per_share: float):
        self.final_valuation_per_share = final_valuation_per_share
        self.final_valuation_total = final_valuation_total
        self.valuation_vs_par = valuation_vs_par
        self.mean_months_paid = mean_months_paid
        self.median_months_paid = median_months_paid
        self.mean_accumulated_unpaid = mean_accumulated_unpaid
        self.mean_npv_per_share = mean_npv_per_share
        self.median_npv_per_share = median_npv_per_share
        self.std_npv_per_share = std_npv_per_share
        self.cv_npv_per_share = cv_npv_per_share


# ============================================================================
# MULTIPROCESSING WORKER FUNCTIONS
# ============================================================================

def simulate_single_dividend_path(initial_cash_reserve: float, initial_bitcoin_holdings: float,
                                 price_path: np.ndarray, config: Dict[str, Any],
                                 threshold_multiplier: Optional[float] = None,
                                 enable_early_termination: bool = True) -> Tuple[int, float, float, float, np.ndarray]:
    """Core dividend simulation logic for a single simulation path with incremental NPV calculation.

    Parameters:
    - initial_cash_reserve: Starting cash reserve
    - initial_bitcoin_holdings: Starting Bitcoin holdings
    - price_path: Array of monthly Bitcoin prices for this simulation
    - config: Configuration dict with simulation parameters
    - threshold_multiplier: Optional override for threshold calculation (default uses config value)

    Returns:
    - months_paid: Number of months dividends were paid
    - final_bitcoin_holdings: Bitcoin holdings at simulation end
    - final_cash_reserve: Cash reserve at simulation end
    - accumulated_unpaid_dividends: Final accumulated unpaid dividends
    - cash_flows: Array of cash flows for each month (for matrix multiplication NPV)
    """
    # Extract config values
    TOTAL_MONTHS = config['total_months']
    SATA_MONTHLY_DIVIDEND_TOTAL = config['sata_monthly_dividend_total']
    TOTAL_PAR_VALUE = config['total_par_value']
    DIVIDEND_SUSPENSION_THRESHOLD_MULTIPLIER = config['dividend_suspension_threshold_multiplier']
    COMPOUNDED_DIVIDEND_START_RATE = config['compounded_dividend_start_rate']
    COMPOUNDED_DIVIDEND_INCREMENT = config['compounded_dividend_increment']
    COMPOUNDED_DIVIDEND_MAX_RATE = config['compounded_dividend_max_rate']
    MONTHLY_DISCOUNT_RATE = config['monthly_discount_rate']

    # Use provided threshold_multiplier or default from config
    threshold_mult = threshold_multiplier if threshold_multiplier is not None else DIVIDEND_SUSPENSION_THRESHOLD_MULTIPLIER

    # Pre-calculate threshold value (constant throughout simulation)
    threshold_value = TOTAL_PAR_VALUE * threshold_mult

    # Cache frequently used values to avoid repeated dictionary lookups
    monthly_dividend_total = SATA_MONTHLY_DIVIDEND_TOTAL
    compounded_start_rate = COMPOUNDED_DIVIDEND_START_RATE
    compounded_increment = COMPOUNDED_DIVIDEND_INCREMENT
    compounded_max_rate = COMPOUNDED_DIVIDEND_MAX_RATE

    # Discount factors now pre-computed in worker functions for matrix multiplication

    # Initialize simulation state
    cash_reserve = initial_cash_reserve
    bitcoin_holdings = initial_bitcoin_holdings
    months_paid = 0
    accumulated_unpaid_dividends = 0.0
    months_unpaid = 0
    cash_flows = np.zeros(TOTAL_MONTHS)  # Cash flows for each month

    consecutive_insolvent_months = 0

    # Simulate each month - this is the 80% bottleneck
    for month in range(TOTAL_MONTHS):
        btc_price = price_path[month]
        bitcoin_value = bitcoin_holdings * btc_price

        # Early termination check: if insolvent for 24+ consecutive months
        if enable_early_termination and bitcoin_holdings <= 0.001 and cash_reserve < monthly_dividend_total and consecutive_insolvent_months >= 24:
            break

        if bitcoin_value >= threshold_value:
            consecutive_insolvent_months = 0  # Reset counter when above threshold

            # Pay accumulated dividends first (ultra-streamlined)
            if accumulated_unpaid_dividends > 0:
                # Fast path: calculate total available resources
                total_available = cash_reserve + bitcoin_holdings * btc_price
                accumulated_payment = min(accumulated_unpaid_dividends, total_available)

                if accumulated_payment > 0:
                    # Optimized deduction: use cash first, then BTC
                    cash_used = min(accumulated_payment, cash_reserve)
                    btc_used = (accumulated_payment - cash_used) / btc_price

                    cash_reserve -= cash_used
                    bitcoin_holdings -= btc_used
                    cash_flows[month] += accumulated_payment  # Record cash flow

                    accumulated_unpaid_dividends -= accumulated_payment
                    months_unpaid = 0 if accumulated_unpaid_dividends <= 0 else months_unpaid

            # Pay regular dividend (ultra-streamlined)
            remaining_value = cash_reserve + bitcoin_holdings * btc_price
            if remaining_value >= monthly_dividend_total:
                # Optimized deduction: same logic as above
                cash_used = min(monthly_dividend_total, cash_reserve)
                btc_used = (monthly_dividend_total - cash_used) / btc_price

                cash_reserve -= cash_used
                bitcoin_holdings -= btc_used
                cash_flows[month] += monthly_dividend_total  # Record cash flow
                months_paid += 1

            elif accumulated_unpaid_dividends <= 0:
                # No payments possible - accumulate with compound rate
                months_unpaid += 1
                compounded_rate = min(compounded_start_rate + (months_unpaid * compounded_increment), compounded_max_rate)
                accumulated_unpaid_dividends += monthly_dividend_total * (1 + compounded_rate/12)
                consecutive_insolvent_months += 1
        else:
            # Bitcoin value below threshold - suspend dividend
            months_unpaid += 1
            compounded_rate = min(compounded_start_rate + (months_unpaid * compounded_increment), compounded_max_rate)
            accumulated_unpaid_dividends += monthly_dividend_total * (1 + compounded_rate/12)
            consecutive_insolvent_months += 1

    return months_paid, bitcoin_holdings, cash_reserve, accumulated_unpaid_dividends, cash_flows

def simulate_unified_worker(args: Tuple[str, Any, np.ndarray, Dict[str, Any]]) -> Any:
    """Unified worker function for all simulation types - eliminates massive code duplication."""
    worker_type, worker_param, price_paths, config = args

    discount_factors = config['discount_factors']

    # Handle different worker types and determine simulation range and array sizes
    if worker_type == 'baseline_chunk':
        sim_start, sim_end = worker_param
        simulation_range = range(sim_start, sim_end)
        array_size = sim_end - sim_start
    else:
        num_simulations = config['num_simulations']
        simulation_range = range(num_simulations)
        array_size = num_simulations

    # Initialize result arrays with correct size
    months_paid = np.zeros(array_size)
    npvs = np.zeros(array_size)
    npvs_per_share = np.zeros(array_size)
    accumulated_unpaid_final = np.zeros(array_size)

    # Configure simulation parameters and price paths based on worker type
    sim_kwargs = {}
    if worker_type == 'scenario':
        # For scenarios, extract price paths from scenario data
        price_paths = np.array(worker_param['price_paths'])
    elif worker_type == 'threshold':
        sim_kwargs['threshold_multiplier'] = worker_param
    elif worker_type == 'dividend_rate':
        # Create modified config for dividend rate sensitivity
        modified_config = config.copy()
        modified_config['sata_annual_dividend_rate'] = worker_param
        modified_config['sata_monthly_dividend_per_share'] = worker_param * config['sata_par_value'] / 12
        modified_config['sata_monthly_dividend_total'] = modified_config['sata_monthly_dividend_per_share'] * config['sata_shares_outstanding']
        sim_kwargs['config_override'] = modified_config
    elif worker_type == 'btc_credit':
        # Calculate BTC holdings for this credit ratio (adjusted BTC credit includes cash)
        # Formula: adjusted_btc_credit = (btc_holdings * btc_price + cash) / total_par_value
        # Rearranged: btc_holdings = (adjusted_btc_credit * total_par_value - cash) / btc_price
        target_total_value = worker_param * config['total_par_value']
        cash = config['initial_cash_reserve']
        required_btc_value = target_total_value - cash
        btc_holdings = max(0, required_btc_value / config['current_bitcoin_price'])
        modified_config = config.copy()
        modified_config['initial_bitcoin_holdings'] = btc_holdings
        sim_kwargs['config_override'] = modified_config

    # Run simulations
    for sim_idx, sim in enumerate(simulation_range):
        # Use shared dividend simulation function
        config_to_use = sim_kwargs.get('config_override', config)

        months, final_btc, final_cash, accumulated_unpaid, cash_flows = simulate_single_dividend_path(
            config_to_use['initial_cash_reserve'],
            config_to_use['initial_bitcoin_holdings'],
            price_paths[sim],
            config_to_use,
            threshold_multiplier=sim_kwargs.get('threshold_multiplier', config_to_use.get('dividend_suspension_threshold_multiplier')),
            enable_early_termination=config_to_use.get('enable_early_termination', True)
        )

        # Calculate NPV
        npv = calculate_npv_matrix_multiplication(cash_flows, discount_factors)

        # Store results
        months_paid[sim_idx] = months
        npvs[sim_idx] = npv
        npvs_per_share[sim_idx] = npv / config['sata_shares_outstanding']
        accumulated_unpaid_final[sim_idx] = accumulated_unpaid

    # Return appropriate result based on worker type
    if worker_type == 'baseline_chunk':
        sim_start, sim_end = worker_param
        return DividendSimulationResult(
            sim_start=sim_start,
            sim_end=sim_end,
            months_dividends_paid=months_paid,
            final_bitcoin_holdings=np.zeros(len(months_paid)),  # Not used in baseline
            final_cash_reserve=np.zeros(len(months_paid)),      # Not used in baseline
            accumulated_unpaid_dividends_final=accumulated_unpaid_final,
            npvs=npvs
        )
    elif worker_type == 'scenario':
        return create_scenario_result(
            scenario_idx=worker_param['idx'],
            starting_price_pct=worker_param['starting_price_pct'],
            starting_price=worker_param['starting_price'],
            mean_npv_per_share=npvs_per_share.mean(),
            median_npv_per_share=np.median(npvs_per_share),
            mean_months_paid=months_paid.mean(),
            std_npv_per_share=npvs_per_share.std(),
            min_npv_per_share=npvs_per_share.min(),
            max_npv_per_share=npvs_per_share.max()
        )
    elif worker_type == 'threshold':
        total_months = config['total_months']
        return create_sensitivity_threshold_result(
            threshold_multiplier=worker_param,
            threshold_value=config['total_par_value'] * worker_param,
            mean_npv_per_share=npvs_per_share.mean(),
            median_npv_per_share=np.median(npvs_per_share),
            mean_months_paid=months_paid.mean(),
            mean_accumulated_unpaid=accumulated_unpaid_final.mean(),
            std_npv_per_share=npvs_per_share.std()
        )
    elif worker_type == 'dividend_rate':
        baseline_rate = config['sata_annual_dividend_rate']
        total_months = config['total_months']
        return create_sensitivity_dividend_rate_result(
            dividend_rate=worker_param,
            dividend_rate_change_pct=((worker_param - baseline_rate) / baseline_rate) * 100,
            mean_npv_per_share=npvs_per_share.mean(),
            median_npv_per_share=np.median(npvs_per_share),
            mean_months_paid=months_paid.mean(),
            mean_accumulated_unpaid=accumulated_unpaid_final.mean(),
            std_npv_per_share=npvs_per_share.std()
        )
    elif worker_type == 'btc_credit':
        total_months = config['total_months']
        return create_sensitivity_btc_credit_result(
            btc_credit_ratio=worker_param,
            btc_holdings=btc_holdings,
            mean_npv_per_share=npvs_per_share.mean(),
            median_npv_per_share=np.median(npvs_per_share),
            mean_months_paid=months_paid.mean(),
            mean_accumulated_unpaid=accumulated_unpaid_final.mean(),
            std_npv_per_share=npvs_per_share.std(),
            npv_per_additional_btc=0.0  # Will be calculated later
        )




# calculate_npv_worker removed - NPV now calculated inline


# ============================================================================
# PLOT GENERATION FUNCTIONS
# ============================================================================

def plot_to_base64(fig):
    """Convert matplotlib figure to base64 string for HTML embedding."""
    buf = io.BytesIO()
    fig.savefig(buf, format='png', bbox_inches='tight', dpi=150)
    buf.seek(0)
    img_base64 = base64.b64encode(buf.read()).decode('utf-8')
    buf.close()
    plt.close(fig)
    return img_base64


def generate_baseline_plots(months_dividends_paid, final_bitcoin_holdings, accumulated_unpaid_dividends_final, plots_dir):
    """Generate plots for baseline scenario analysis showing dividend sustainability and Bitcoin holdings distribution."""
    os.makedirs(plots_dir, exist_ok=True)
    
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    
    axes[0].hist(months_dividends_paid, bins=50, edgecolor='k', alpha=0.7)
    axes[0].axvline(months_dividends_paid.mean(), color='r', linestyle='--', 
                    label=f'Mean: {months_dividends_paid.mean():.1f}')
    axes[0].set_xlabel('Months Dividends Paid')
    axes[0].set_ylabel('Frequency')
    axes[0].set_title('Distribution of Months Dividends Can Be Paid')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)
    
    axes[1].hist(final_bitcoin_holdings, bins=50, edgecolor='k', alpha=0.7)
    axes[1].set_xlabel('Final Bitcoin Holdings (BTC)')
    axes[1].set_ylabel('Frequency')
    axes[1].set_title('Distribution of Final Bitcoin Holdings')
    axes[1].grid(True, alpha=0.3)
    
    plt.tight_layout()
    filepath = os.path.join(plots_dir, 'baseline_dividend_sustainability.png')
    plt.savefig(filepath, bbox_inches='tight', dpi=150)
    img_base64 = plot_to_base64(fig)
    
    return filepath, img_base64


def generate_npv_plots(npvs_per_share, months_dividends_paid, plots_dir):
    """Generate plots showing NPV per share distribution and correlation with months of dividend payments."""
    os.makedirs(plots_dir, exist_ok=True)
    
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    
    axes[0].hist(npvs_per_share, bins=100, edgecolor='k', alpha=0.7)
    axes[0].axvline(npvs_per_share.mean(), color='r', linestyle='--', linewidth=2,
                    label=f'Mean: ${npvs_per_share.mean():,.2f}')
    axes[0].axvline(np.median(npvs_per_share), color='g', linestyle='--', linewidth=2,
                    label=f'Median: ${np.median(npvs_per_share):,.2f}')
    axes[0].set_xlabel('NPV per Share (USD)')
    axes[0].set_ylabel('Frequency')
    axes[0].set_title('Distribution of NPV per Share')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)
    
    axes[1].scatter(months_dividends_paid, npvs_per_share, alpha=0.1, s=1)
    axes[1].set_xlabel('Months Dividends Paid')
    axes[1].set_ylabel('NPV per Share (USD)')
    axes[1].set_title('NPV vs. Months Dividends Paid')
    axes[1].grid(True, alpha=0.3)
    
    plt.tight_layout()
    filepath = os.path.join(plots_dir, 'baseline_npv_distribution.png')
    plt.savefig(filepath, bbox_inches='tight', dpi=150)
    img_base64 = plot_to_base64(fig)
    
    return filepath, img_base64


def generate_scenario_plots(results_df, num_scenarios, plots_dir, baseline_npv=None):
    """Generate plots for multi-scenario NPV analysis across different Bitcoin starting prices, showing NPV trends and dividend sustainability."""
    os.makedirs(plots_dir, exist_ok=True)
    
    fig, axes = plt.subplots(2, 1, figsize=(14, 10))
    
    x_data = results_df['starting_price_pct'] * 100
    y_data = results_df['mean_npv_per_share']
    
    axes[0].plot(x_data, y_data, marker='o', linewidth=2, markersize=8, color='blue', 
                 label='Mean NPV per Share')
    
    slope, intercept = np.polyfit(x_data, y_data, 1)
    trend_line = slope * x_data + intercept
    axes[0].plot(x_data, trend_line, linestyle='--', linewidth=2, color='red', alpha=0.7,
                 label=f'Trend Line (slope: ${slope:.2f}/%)')
    
    axes[0].axvline(x=0, color='green', linestyle='--', linewidth=1.5, alpha=0.7, label='Baseline (0%)')
    # Use provided baseline NPV or find it in results
    if baseline_npv is not None:
        plot_baseline_npv = baseline_npv
    else:
        baseline_mask = np.isclose(results_df['starting_price_pct'], 0, atol=1e-6)
        plot_baseline_npv = results_df[baseline_mask]['mean_npv_per_share'].values[0] if baseline_mask.sum() > 0 else results_df['mean_npv_per_share'].iloc[num_scenarios//2]
    axes[0].axhline(y=plot_baseline_npv, color='green', linestyle='--', linewidth=1.5, alpha=0.7)
    axes[0].set_xlabel('Starting Price Percentage Change (%)', fontsize=12)
    axes[0].set_ylabel('Mean NPV per Share (USD)', fontsize=12)
    axes[0].set_title('SATA NPV vs Bitcoin Starting Price', fontsize=14, fontweight='bold')
    axes[0].grid(True, alpha=0.3)
    axes[0].legend(fontsize=11)
    
    for idx, row in results_df.iterrows():
        if idx % 2 == 0:
            axes[0].annotate(f'${row["mean_npv_per_share"]:,.0f}',
                           (row['starting_price_pct'] * 100, row['mean_npv_per_share']),
                           textcoords="offset points", xytext=(0,10), ha='center', fontsize=8)
    
    axes[1].plot(results_df['starting_price_pct'] * 100, results_df['mean_months_paid'],
                 marker='s', linewidth=2, markersize=8, color='orange', label='Mean Months Paid')
    axes[1].axvline(x=0, color='green', linestyle='--', linewidth=1.5, alpha=0.7, label='Baseline (0%)')
    axes[1].set_xlabel('Starting Price Percentage Change (%)', fontsize=12)
    axes[1].set_ylabel('Mean Months Dividends Paid', fontsize=12)
    axes[1].set_title('Dividend Sustainability vs Bitcoin Starting Price', fontsize=14, fontweight='bold')
    axes[1].grid(True, alpha=0.3)
    axes[1].legend(fontsize=11)
    
    plt.tight_layout()
    filepath = os.path.join(plots_dir, 'scenario_analysis.png')
    plt.savefig(filepath, bbox_inches='tight', dpi=150)
    img_base64 = plot_to_base64(fig)
    
    return filepath, img_base64, slope, intercept


def generate_sensitivity_plots(sensitivity_df, default_threshold, plots_dir):
    """Generate plots for dividend suspension threshold sensitivity analysis, showing NPV and dividend sustainability across threshold multipliers."""
    os.makedirs(plots_dir, exist_ok=True)

    fig, axes = plt.subplots(2, 1, figsize=(14, 8))

    axes[0].plot(sensitivity_df['threshold_multiplier'], sensitivity_df['mean_npv_per_share'],
                 marker='o', linewidth=2, markersize=8, color='blue', label='Mean NPV per Share')
    axes[0].axvline(x=default_threshold, color='red', linestyle='--', linewidth=1.5, alpha=0.7,
                    label=f'Default ({default_threshold:.2f}x)')
    axes[0].set_xlabel('Suspension Threshold Multiplier (x par value)', fontsize=12)
    axes[0].set_ylabel('Mean NPV per Share (USD)', fontsize=12)
    axes[0].set_title('NPV vs Dividend Suspension Threshold', fontsize=14, fontweight='bold')
    axes[0].grid(True, alpha=0.3)
    axes[0].legend(fontsize=11)

    axes[1].plot(sensitivity_df['threshold_multiplier'], sensitivity_df['mean_months_paid'],
                 marker='s', linewidth=2, markersize=8, color='orange', label='Mean Months Paid')
    axes[1].axvline(x=default_threshold, color='red', linestyle='--', linewidth=1.5, alpha=0.7,
                    label=f'Default ({default_threshold:.2f}x)')
    axes[1].set_xlabel('Suspension Threshold Multiplier (x par value)', fontsize=12)
    axes[1].set_ylabel('Mean Months Dividends Paid', fontsize=12)
    axes[1].set_title('Dividend Sustainability vs Suspension Threshold', fontsize=14, fontweight='bold')
    axes[1].grid(True, alpha=0.3)
    axes[1].legend(fontsize=11)

    plt.tight_layout()
    filepath = os.path.join(plots_dir, 'sensitivity_analysis.png')
    plt.savefig(filepath, bbox_inches='tight', dpi=150)
    img_base64 = plot_to_base64(fig)

    return filepath, img_base64


def generate_dividend_rate_sensitivity_plots(dividend_rate_sensitivity_df, baseline_dividend_rate, plots_dir):
    """Generate plots for dividend rate sensitivity analysis, showing how NPV and dividend payments change with different dividend rates."""
    os.makedirs(plots_dir, exist_ok=True)

    fig, axes = plt.subplots(2, 1, figsize=(14, 8))

    # Plot NPV vs Dividend Rate
    axes[0].plot(dividend_rate_sensitivity_df['dividend_rate'] * 100, dividend_rate_sensitivity_df['mean_npv_per_share'],
                 marker='o', linewidth=2, markersize=8, color='blue', label='Mean NPV per Share')
    axes[0].axvline(x=baseline_dividend_rate * 100, color='red', linestyle='--', linewidth=1.5, alpha=0.7,
                    label=f'Baseline ({baseline_dividend_rate:.2%})')
    axes[0].set_xlabel('Dividend Rate (%)', fontsize=12)
    axes[0].set_ylabel('Mean NPV per Share (USD)', fontsize=12)
    axes[0].set_title('NPV vs Dividend Rate', fontsize=14, fontweight='bold')
    axes[0].grid(True, alpha=0.3)
    axes[0].legend(fontsize=11)

    # Plot Months Paid vs Dividend Rate
    axes[1].plot(dividend_rate_sensitivity_df['dividend_rate'] * 100, dividend_rate_sensitivity_df['mean_months_paid'],
                 marker='s', linewidth=2, markersize=8, color='orange', label='Mean Months Paid')
    axes[1].axvline(x=baseline_dividend_rate * 100, color='red', linestyle='--', linewidth=1.5, alpha=0.7,
                    label=f'Baseline ({baseline_dividend_rate:.2%})')
    axes[1].set_xlabel('Dividend Rate (%)', fontsize=12)
    axes[1].set_ylabel('Mean Months Dividends Paid', fontsize=12)
    axes[1].set_title('Dividend Sustainability vs Dividend Rate', fontsize=14, fontweight='bold')
    axes[1].grid(True, alpha=0.3)
    axes[1].legend(fontsize=11)

    plt.tight_layout()
    filepath = os.path.join(plots_dir, 'dividend_rate_sensitivity_analysis.png')
    plt.savefig(filepath, bbox_inches='tight', dpi=150)
    img_base64 = plot_to_base64(fig)

    return filepath, img_base64


def generate_btc_credit_sensitivity_plots(btc_credit_sensitivity_df, current_btc_credit, plots_dir):
    """Generate plots for BTC credit sensitivity analysis, showing NPV and dividend sustainability across different BTC credit ratios."""
    os.makedirs(plots_dir, exist_ok=True)

    fig, axes = plt.subplots(2, 1, figsize=(14, 8))

    # Plot NPV vs BTC Credit Ratio
    axes[0].plot(btc_credit_sensitivity_df['btc_credit_ratio'], btc_credit_sensitivity_df['mean_npv_per_share'],
                 marker='o', linewidth=2, markersize=8, color='blue', label='Mean NPV per Share')
    axes[0].axvline(x=current_btc_credit, color='red', linestyle='--', linewidth=1.5, alpha=0.7,
                    label=f'Current BTC Credit ({current_btc_credit:.4f}x)')
    axes[0].set_xlabel('BTC Credit Ratio', fontsize=12)
    axes[0].set_ylabel('Mean NPV per Share (USD)', fontsize=12)
    axes[0].set_title('NPV vs BTC Credit Ratio', fontsize=14, fontweight='bold')
    axes[0].grid(True, alpha=0.3)
    axes[0].legend(fontsize=11)

    # Plot Months Paid vs BTC Credit Ratio
    axes[1].plot(btc_credit_sensitivity_df['btc_credit_ratio'], btc_credit_sensitivity_df['mean_months_paid'],
                 marker='s', linewidth=2, markersize=8, color='orange', label='Mean Months Paid')
    axes[1].axvline(x=current_btc_credit, color='red', linestyle='--', linewidth=1.5, alpha=0.7,
                    label=f'Current BTC Credit ({current_btc_credit:.4f}x)')
    axes[1].set_xlabel('BTC Credit Ratio', fontsize=12)
    axes[1].set_ylabel('Mean Months Dividends Paid', fontsize=12)
    axes[1].set_title('Dividend Sustainability vs BTC Credit Ratio', fontsize=14, fontweight='bold')
    axes[1].grid(True, alpha=0.3)
    axes[1].legend(fontsize=11)

    plt.tight_layout()
    filepath = os.path.join(plots_dir, 'btc_credit_sensitivity_analysis.png')
    plt.savefig(filepath, bbox_inches='tight', dpi=150)
    img_base64 = plot_to_base64(fig)

    return filepath, img_base64


# ============================================================================
# JSON RESULTS OUTPUT
# ============================================================================

def save_results_to_json(results_data: Dict[str, Any], output_file: str) -> None:
    """Save analysis results to JSON file for later HTML generation."""
    import json

    # Convert numpy types to native Python types for JSON serialization
    def convert_numpy_types(obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        elif isinstance(obj, dict):
            return {key: convert_numpy_types(value) for key, value in obj.items()}
        elif isinstance(obj, list):
            return [convert_numpy_types(item) for item in obj]
        elif hasattr(obj, '__dict__'):
            # Convert objects to dictionaries
            return convert_numpy_types(obj.__dict__)
        else:
            return obj

    json_data = convert_numpy_types(results_data)

    with open(output_file, 'w') as f:
        json.dump(json_data, f, indent=2)

    print(f"✓ Results saved to: {output_file}")


# ============================================================================
# ANALYSIS FUNCTIONS
# ============================================================================

def setup_configuration_and_data(args) -> Tuple[Configuration, Dict[str, Any], np.ndarray]:
    """Load and setup configuration, price data, and baseline price paths."""

    # Load configuration
    logger.info("="*70)
    logger.info("LOADING CONFIGURATION")
    logger.info("="*70)
    strive_data = load_btcc_data(args.data_dir)

    # Load price paths
    logger.info("="*70)
    logger.info("LOADING BITCOIN PRICE PATHS")
    logger.info("="*70)
    price_data = load_price_paths(args.data_dir)

    # Create configuration with overrides from JSON data
    config = Configuration(**strive_data)
    config.optimization_level = args.optimization_level
    config.enable_early_termination = args.optimization_level >= 1
    config.validate()

    # Extract price data parameters
    NUM_SIMULATIONS = price_data['num_simulations']
    scenarios = price_data['scenarios']
    # Find the scenario with starting price change closest to 0% (baseline)
    baseline_scenario_idx = min(range(len(scenarios)),
                               key=lambda i: abs(scenarios[i]['starting_price_pct']))
    baseline_scenario = scenarios[baseline_scenario_idx]
    baseline_price_paths = np.array(baseline_scenario['price_paths'])

    # Update config with price data parameters
    config_dict = config.to_dict()
    config_dict.update({
        'num_simulations': NUM_SIMULATIONS,
        'simulation_years': price_data['simulation_years'],
        'total_months': price_data['total_months'],
        'current_bitcoin_price': price_data['current_bitcoin_price']
    })

    logger.info("="*70)
    logger.info("CONFIGURATION SUMMARY")
    logger.info("="*70)
    logger.info(f"Simulations: {price_data['num_simulations']:,}")
    logger.info(f"Projection Period: {price_data['simulation_years']} years ({price_data['total_months']:,} months)")
    logger.info(f"SATA Shares Outstanding: {config.sata_shares_outstanding:,}")
    logger.info(f"SATA Dividend Rate: {config.sata_annual_dividend_rate:.2%}")
    logger.info(f"Total Monthly Dividend: ${config.sata_monthly_dividend_total:,.2f}")
    logger.info(f"Initial Bitcoin Holdings: {config.initial_bitcoin_holdings:,.2f} BTC")
    logger.info(f"Initial Cash Reserve: ${config.initial_cash_reserve:,.0f}")
    logger.info(f"Discount Rate (Annual): {config.discount_rate_annual:.2%}")
    logger.info(f"Suspension Threshold: {config.dividend_suspension_threshold_multiplier:.2f}x par value")

    return config, config_dict, baseline_price_paths


def run_baseline_analysis(baseline_price_paths: np.ndarray, config_dict: Dict[str, Any],
                         num_workers: int) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Run baseline scenario dividend sustainability analysis with optimized chunking."""

    print("\n" + "="*70)
    print("BASELINE SCENARIO: DIVIDEND SUSTAINABILITY ANALYSIS")
    print("="*70)
    print(f"Calculating dividend sustainability for {config_dict['num_simulations']:,} simulations...")

    # Optimized chunking: larger chunks reduce overhead (80/20 optimization)
    chunk_size = max(500, config_dict['num_simulations'] // (num_workers * 2))  # Fewer, larger chunks
    chunks = []
    for i in range(0, config_dict['num_simulations'], chunk_size):
        chunk_param = (i, min(i + chunk_size, config_dict['num_simulations']))
        chunks.append(('baseline_chunk', chunk_param, baseline_price_paths, config_dict))

    # Execute in parallel with fallback
    baseline_results = execute_parallel_with_fallback(
        simulate_unified_worker, chunks, num_workers, "simulation chunks"
    )

    # Combine results efficiently - direct array operations (faster than list comprehensions)
    months_dividends_paid = np.concatenate([r.months_dividends_paid for r in baseline_results])
    final_bitcoin_holdings = np.concatenate([r.final_bitcoin_holdings for r in baseline_results])
    final_cash_reserve = np.concatenate([r.final_cash_reserve for r in baseline_results])
    accumulated_unpaid_dividends_final = np.concatenate([r.accumulated_unpaid_dividends_final for r in baseline_results])
    npvs = np.concatenate([r.npvs for r in baseline_results])

    # Immediate cleanup to free memory
    del baseline_results
    gc.collect()

    print(f"\n✓ Baseline scenario complete!")
    full_payment_mask = months_dividends_paid == config_dict['total_months']
    print(f"  Average months paid: {months_dividends_paid.mean():.1f}")
    print(f"  Median months paid: {np.median(months_dividends_paid):.1f}")
    print(f"  Average NPV per share: ${npvs.mean():,.2f}")
    print(f"  Simulations that paid full period: {full_payment_mask.sum():,} ({full_payment_mask.mean()*100:.1f}%)")

    return months_dividends_paid, final_bitcoin_holdings, final_cash_reserve, accumulated_unpaid_dividends_final, npvs


# calculate_baseline_npv removed - NPV now calculated inline in baseline analysis


def run_scenario_analysis(scenarios: List[Dict], config_dict: Dict[str, Any],
                         num_workers: int) -> np.ndarray:
    """Execute multi-scenario NPV analysis across different Bitcoin starting price assumptions, calculating valuation impact for each scenario."""

    if len(scenarios) <= 1:
        return np.array([], dtype=RESULT_DTYPE)

    # Find the baseline scenario (starting_price_pct closest to 0)
    baseline_scenario_idx = min(range(len(scenarios)),
                               key=lambda i: abs(scenarios[i]['starting_price_pct']))

    # Filter out the baseline scenario (starting_price_pct closest to 0)
    non_baseline_scenarios = []
    non_baseline_indices = []
    for i, scenario in enumerate(scenarios):
        if abs(scenario['starting_price_pct']) > 0.001:  # Not the baseline
            non_baseline_scenarios.append(scenario)
            non_baseline_indices.append(i)

    if len(non_baseline_scenarios) == 0:
        return np.array([], dtype=RESULT_DTYPE)

    print("\n" + "="*70)
    print("MULTI-SCENARIO NPV ANALYSIS")
    print("="*70)
    print(f"Calculating NPV for {len(non_baseline_scenarios)} scenarios (excluding redundant baseline)...")

    # Create tasks for parallel scenario processing (only non-baseline scenarios)
    scenario_args = [('scenario', {'idx': original_idx, **non_baseline_scenarios[i]}, None, config_dict)
                    for i, original_idx in enumerate(non_baseline_indices)]

    # Execute in parallel with fallback
    scenario_results = execute_parallel_with_fallback(
        simulate_unified_worker, scenario_args, num_workers, "scenarios"
    )

    # Add baseline result (which was already calculated)
    # Get baseline statistics from config_dict
    baseline_npv_mean = config_dict.get('baseline_npv_per_share_mean', 0)
    baseline_npv_median = config_dict.get('baseline_npv_per_share_median', 0)
    baseline_npv_std = config_dict.get('baseline_npv_per_share_std', 0)
    baseline_months_mean = config_dict.get('baseline_months_paid_mean', 0)

    baseline_result = create_scenario_result(
        scenario_idx=baseline_scenario_idx,
        starting_price_pct=scenarios[baseline_scenario_idx]['starting_price_pct'],
        starting_price=scenarios[baseline_scenario_idx]['starting_price'],
        mean_npv_per_share=baseline_npv_mean,
        median_npv_per_share=baseline_npv_median,
        mean_months_paid=baseline_months_mean,
        std_npv_per_share=baseline_npv_std,
        min_npv_per_share=baseline_npv_mean,  # For baseline scenario, min=max=mean
        max_npv_per_share=baseline_npv_mean
    )

    # Convert list of structured arrays to single concatenated array
    if len(scenario_results) > 0:
        all_results = np.concatenate(scenario_results + [baseline_result])
    else:
        all_results = baseline_result

    # Sort by scenario index
    sort_indices = np.argsort(all_results['scenario_idx'])
    all_results = all_results[sort_indices]

    print(f"\n✓ Multi-scenario analysis complete! (including baseline)")
    return all_results


def run_unified_sensitivity_analysis(analysis_type: str, baseline_price_paths: np.ndarray,
                                        config: Configuration, config_dict: Dict[str, Any],
                                        num_workers: int) -> np.ndarray:
    """Unified sensitivity analysis runner for all sensitivity types - eliminates massive code duplication."""

    # Analysis type configuration
    analysis_configs = {
        'threshold': {
            'title': 'DIVIDEND SUSPENSION THRESHOLD',
            'param_method': 'get_sensitivity_thresholds',
            'param_name': 'threshold multipliers',
            'range_info': lambda c: f"  Range: {c.sensitivity_threshold_start:.2f}x to {c.sensitivity_threshold_end:.2f}x (step: {c.sensitivity_threshold_step:.2f})",
            'create_baseline': lambda c, stats: create_sensitivity_threshold_result(
                threshold_multiplier=c.dividend_suspension_threshold_multiplier,
                threshold_value=c.dividend_suspension_threshold_multiplier * c.total_par_value,
                mean_npv_per_share=stats['npv_mean'],
                median_npv_per_share=stats['npv_median'],
                mean_months_paid=stats['months_mean'],
                mean_accumulated_unpaid=stats['accumulated_mean'],
                std_npv_per_share=stats['npv_std']
            ),
            'sort_key': 'threshold_multiplier'
        },
        'dividend_rate': {
            'title': 'DIVIDEND RATE',
            'param_method': 'get_dividend_rate_sensitivity_values',
            'param_name': 'dividend rates',
            'range_info': lambda c: f"  Baseline rate: {c.sata_annual_dividend_rate:.2%}\n  Range: {c.sata_annual_dividend_rate * (1 + c.dividend_rate_sensitivity_start_pct/100):.2%} to {c.sata_annual_dividend_rate * (1 + c.dividend_rate_sensitivity_end_pct/100):.2%}",
            'create_baseline': lambda c, stats: create_sensitivity_dividend_rate_result(
                dividend_rate=c.sata_annual_dividend_rate,
                dividend_rate_change_pct=0.0,
                mean_npv_per_share=stats['npv_mean'],
                median_npv_per_share=stats['npv_median'],
                mean_months_paid=stats['months_mean'],
                mean_accumulated_unpaid=stats['accumulated_mean'],
                std_npv_per_share=stats['npv_std']
            ),
            'sort_key': 'dividend_rate'
        },
        'btc_credit': {
            'title': 'BTC CREDIT',
            'param_method': None,  # Calculated inline
            'param_name': 'BTC credit ratios',
            'range_info': lambda c: f"  Current BTC credit: {config_dict.get('baseline_btc_credit', 1.0):.4f}x\n  Range: ±1.0x from current (step: 0.25x)",
            'create_baseline': lambda c, stats: create_sensitivity_btc_credit_result(
                btc_credit_ratio=config_dict.get('baseline_btc_credit', 1.0),
                btc_holdings=c.initial_bitcoin_holdings,
                mean_npv_per_share=stats['npv_mean'],
                median_npv_per_share=stats['npv_median'],
                mean_months_paid=stats['months_mean'],
                mean_accumulated_unpaid=stats['accumulated_mean'],
                std_npv_per_share=stats['npv_std'],
                npv_per_additional_btc=0.0
            ),
            'sort_key': 'btc_credit_ratio'
        }
    }

    if analysis_type not in analysis_configs:
        raise ValueError(f"Unknown analysis type: {analysis_type}")

    cfg = analysis_configs[analysis_type]

    print("\n" + "="*70)
    print(f"SENSITIVITY ANALYSIS: {cfg['title']}")
    print("="*70)

    # Get parameters using the configured method or calculate inline
    if cfg['param_method'] is not None:
        param_method = getattr(config, cfg['param_method'])
        parameters = param_method()
    else:
        # Calculate BTC credit ratios inline (same logic as original)
        current_btc_credit = config_dict['baseline_btc_credit']
        range_half_width = 1.0
        step_size = 0.25
        start_ratio = max(0.25, current_btc_credit - range_half_width)
        end_ratio = current_btc_credit + range_half_width
        parameters = np.arange(start_ratio, end_ratio + step_size, step_size)
        # Exclude the baseline BTC credit ratio to avoid redundant calculation
        parameters = parameters[np.abs(parameters - current_btc_credit) > 1e-4]

    print(f"Testing {len(parameters)} {cfg['param_name']}...")
    print(cfg['range_info'](config))

    # Create tasks for parallel sensitivity analysis
    sensitivity_args = [(analysis_type, param, baseline_price_paths, config_dict) for param in parameters]

    # Execute in parallel with fallback
    sensitivity_results = execute_parallel_with_fallback(
        simulate_unified_worker, sensitivity_args, num_workers, cfg['param_name']
    )

    # Add baseline result
    baseline_stats = {
        'npv_mean': config_dict.get('baseline_npv_per_share_mean', 0),
        'npv_median': config_dict.get('baseline_npv_per_share_median', 0),
        'npv_std': config_dict.get('baseline_npv_per_share_std', 0),
        'months_mean': config_dict.get('baseline_months_paid_mean', 0),
        'accumulated_mean': config_dict.get('baseline_accumulated_unpaid_mean', 0)
    }

    baseline_result = cfg['create_baseline'](config, baseline_stats)

    # Combine results and sort
    if len(sensitivity_results) > 0:
        # Flatten all results to ensure consistent 1D arrays
        all_arrays = []
        for r in sensitivity_results:
            if hasattr(r, 'flatten'):
                all_arrays.append(r.flatten())
            else:
                all_arrays.append(np.array([r]))
        if hasattr(baseline_result, 'flatten'):
            all_arrays.append(baseline_result.flatten())
        else:
            all_arrays.append(np.array([baseline_result]))
        all_results = np.concatenate(all_arrays)
    else:
        if hasattr(baseline_result, 'flatten'):
            all_results = baseline_result.flatten()
        else:
            all_results = np.array([baseline_result])
    sort_indices = np.argsort(all_results[cfg['sort_key']])
    all_results = all_results[sort_indices]

    return all_results




# ============================================================================
# MAIN EXECUTION
# ============================================================================

def validate_arguments(args) -> None:
    """Validate command line arguments."""
    if args.num_workers is not None and args.num_workers < 1:
        raise ValueError("Number of workers must be positive")

    # Check if output directory is writable (skip in sandbox environments)
    output_dir = os.path.dirname(args.output) or '.'
    try:
        if not os.access(output_dir, os.W_OK):
            logger.warning(f"Cannot verify write access to output directory: {output_dir}")
    except (OSError, PermissionError):
        logger.warning(f"Cannot check write access to output directory: {output_dir}")

    try:
        os.makedirs(args.data_dir, exist_ok=True)
    except (OSError, PermissionError):
        logger.warning(f"Cannot create data directory: {args.data_dir}")

    # Check if plots directory is writable
    try:
        if not os.access(args.plots_dir, os.W_OK):
            os.makedirs(args.plots_dir, exist_ok=True)
    except (OSError, PermissionError):
        logger.warning(f"Cannot create plots directory: {args.plots_dir}")


def main() -> None:
    """Main entry point for SATA valuation analysis."""
    start_time = time.time()

    parser = argparse.ArgumentParser(description='SATA Preferred Equity Valuation Model')
    parser.add_argument(
        '--data-dir',
        type=str,
        default=str(DEFAULT_OUTPUT_DIR),
        help=f'Directory for treasury JSON and BTC price path files (default: {DEFAULT_OUTPUT_DIR})',
    )
    parser.add_argument('--output', type=str, default=str(DEFAULT_OUTPUT_DIR / 'sata_valuation_results.json'),
                       help=f'Output JSON results file path (default: {DEFAULT_OUTPUT_DIR / "sata_valuation_results.json"})')
    parser.add_argument('--plots-dir', type=str, default=str(DEFAULT_PLOTS_DIR),
                       help=f'Directory for plot images (default: {DEFAULT_PLOTS_DIR})')
    parser.add_argument('--num-workers', type=int, default=None,
                       help='Number of worker processes (default: CPU count)')
    parser.add_argument('--optimization-level', type=int, default=2, choices=[0, 1, 2],
                       help='Optimization level: 0=baseline, 1=moderate, 2=aggressive (default: 2)')
    parser.add_argument('--baseline-only', action='store_true',
                       help='Run only baseline scenario analysis for performance testing')

    args = parser.parse_args()

    ensure_output_dirs()
    os.makedirs(args.data_dir, exist_ok=True)
    os.makedirs(args.plots_dir, exist_ok=True)
    out_parent = os.path.dirname(os.path.abspath(args.output)) or '.'
    os.makedirs(out_parent, exist_ok=True)

    # Validate arguments
    validate_arguments(args)

    # Setup configuration and data
    config, config_dict, baseline_price_paths = setup_configuration_and_data(args)

    num_workers = args.num_workers or config.default_num_workers or cpu_count()
    print(f"Using {num_workers} worker processes")

    # Pre-compute discount factors once - they never change across all scenarios
    total_months = config_dict['total_months']
    monthly_discount_rate = config_dict['monthly_discount_rate']
    discount_factors = np.power(1 + monthly_discount_rate, np.arange(1, total_months + 1))
    config_dict['discount_factors'] = discount_factors  # Add to config for reuse
    
    months_dividends_paid, final_bitcoin_holdings, final_cash_reserve, accumulated_unpaid_dividends_final, npvs = run_baseline_analysis(baseline_price_paths, config_dict, num_workers)
    npvs_per_share = npvs / config.sata_shares_outstanding

    # Store baseline statistics for sensitivity analysis baseline inclusion
    config_dict['baseline_npv_per_share_mean'] = npvs_per_share.mean()
    config_dict['baseline_npv_per_share_median'] = np.median(npvs_per_share)
    config_dict['baseline_npv_per_share_std'] = npvs_per_share.std()
    config_dict['baseline_months_paid_mean'] = months_dividends_paid.mean()
    config_dict['baseline_accumulated_unpaid_mean'] = accumulated_unpaid_dividends_final.mean()

    # Calculate and store baseline values
    # Adjusted BTC credit includes cash: (btc_holdings * btc_price + cash) / total_par_value
    current_btc_price = config_dict.get('current_bitcoin_price', 87057.08)
    adjusted_btc_value = config.initial_bitcoin_holdings * current_btc_price + config.initial_cash_reserve
    config_dict.update({
        'baseline_btc_credit': adjusted_btc_value / config.total_par_value,
        'baseline_dividend_rate': config.sata_annual_dividend_rate,
        'baseline_btc_holdings': config.initial_bitcoin_holdings
    })

    FINAL_VALUATION_PER_SHARE = npvs_per_share.mean()
    baseline_results = BaselineResults(
        final_valuation_per_share=FINAL_VALUATION_PER_SHARE,
        final_valuation_total=npvs.mean(),
        valuation_vs_par=(FINAL_VALUATION_PER_SHARE / config.sata_par_value - 1) * 100,
        mean_months_paid=config_dict['baseline_months_paid_mean'],
        median_months_paid=np.median(months_dividends_paid),
        mean_accumulated_unpaid=config_dict['baseline_accumulated_unpaid_mean'],
        mean_npv_per_share=FINAL_VALUATION_PER_SHARE,
        median_npv_per_share=config_dict['baseline_npv_per_share_median'],
        std_npv_per_share=config_dict['baseline_npv_per_share_std'],
        cv_npv_per_share=config_dict['baseline_npv_per_share_std'] / FINAL_VALUATION_PER_SHARE
    )

    # Generate baseline plots
    print("\nGenerating baseline plots...")
    _, img1 = generate_baseline_plots(months_dividends_paid, final_bitcoin_holdings,
                                     accumulated_unpaid_dividends_final, args.plots_dir)
    _, img2 = generate_npv_plots(npvs_per_share, months_dividends_paid, args.plots_dir)
    plot_images = {
        'baseline_dividend_sustainability': img1,
        'baseline_npv_distribution': img2
    }

    # If baseline-only mode, skip all other analyses for performance testing
    if args.baseline_only:
        print("\n" + "="*70)
        print("BASELINE-ONLY MODE: Performance testing core simulation")
        print("="*70)

        results_data = {
            'metadata': {
                'timestamp': datetime.now().isoformat(),
                'version': '1.0',
                'mode': 'baseline_only'
            },
            'configuration': config_dict,
            'baseline_results': baseline_results.__dict__,
            'scenario_results': [],
            'sensitivity_results': [],
            'dividend_rate_sensitivity_results': [],
            'btc_credit_sensitivity_results': [],
            'plot_images': plot_images
        }

        json_file = args.output.replace('.html', '.json')
        save_results_to_json(results_data, json_file)

        # Calculate and display execution time
        end_time = time.time()
        total_time = end_time - start_time

        print("\n" + "="*70)
        print("BASELINE-ONLY ANALYSIS COMPLETE")
        print("="*70)
        print(f"✓ Results saved to: {json_file}")
        print(f"✓ Plots saved to: {args.plots_dir}/")
        print(f"✓ Total execution time: {total_time:.2f} seconds")
        print(f"✓ Core simulation performance: {total_time:.2f}s for {config_dict['num_simulations']:,} simulations")

        return

    # Load price data for scenario analysis
    price_data = load_price_paths(args.data_dir)
    scenarios = price_data['scenarios']

    # Run multi-scenario analysis
    scenario_results = run_scenario_analysis(scenarios, config_dict, num_workers)

    if len(scenario_results) > 0:
        # Generate scenario plots
        print("\nGenerating scenario plots...")
        results_df = pd.DataFrame([{
            'starting_price_pct': r['starting_price_pct'],
            'starting_price': r['starting_price'],
            'mean_npv_per_share': r['mean_npv_per_share'],
            'mean_months_paid': r['mean_months_paid']
        } for r in scenario_results])

        _, img3, slope, intercept = generate_scenario_plots(results_df, len(scenario_results), args.plots_dir, FINAL_VALUATION_PER_SHARE)

        r_squared = np.corrcoef(results_df['starting_price_pct'] * 100, results_df['mean_npv_per_share'])[0,1]**2

        plot_images['scenario_analysis'] = img3
        plot_images['trend_slope'] = slope
        plot_images['trend_intercept'] = intercept
        plot_images['trend_r_squared'] = r_squared

    print("\n" + "="*70)
    print("RUNNING ALL SENSITIVITY ANALYSES")
    print("="*70)

    # Sensitivity analyses with inline plot generation
    sensitivity_results = run_unified_sensitivity_analysis('threshold', baseline_price_paths, config, config_dict, num_workers)
    sensitivity_df = pd.DataFrame([{'threshold_multiplier': r['threshold_multiplier'], 'threshold_value': r['threshold_value'], 'mean_npv_per_share': r['mean_npv_per_share'], 'mean_months_paid': r['mean_months_paid'], 'mean_accumulated_unpaid': r['mean_accumulated_unpaid'], 'std_npv_per_share': r['std_npv_per_share']} for r in sensitivity_results])
    plot_images['sensitivity_analysis'] = generate_sensitivity_plots(sensitivity_df, config.dividend_suspension_threshold_multiplier, args.plots_dir)[1]

    dividend_rate_sensitivity_results = run_unified_sensitivity_analysis('dividend_rate', baseline_price_paths, config, config_dict, num_workers)
    dividend_rate_sensitivity_df = pd.DataFrame([{'dividend_rate': r['dividend_rate'], 'dividend_rate_change_pct': r['dividend_rate_change_pct'], 'mean_npv_per_share': r['mean_npv_per_share'], 'median_npv_per_share': r['median_npv_per_share'], 'mean_months_paid': r['mean_months_paid'], 'mean_accumulated_unpaid': r['mean_accumulated_unpaid'], 'std_npv_per_share': r['std_npv_per_share']} for r in dividend_rate_sensitivity_results])
    plot_images['dividend_rate_sensitivity_analysis'] = generate_dividend_rate_sensitivity_plots(dividend_rate_sensitivity_df, config.sata_annual_dividend_rate, args.plots_dir)[1]

    btc_credit_sensitivity_results = run_unified_sensitivity_analysis('btc_credit', baseline_price_paths, config, config_dict, num_workers)
    btc_credit_sensitivity_df = pd.DataFrame([{'btc_credit_ratio': r['btc_credit_ratio'], 'btc_holdings': r['btc_holdings'], 'mean_npv_per_share': r['mean_npv_per_share'], 'median_npv_per_share': r['median_npv_per_share'], 'mean_months_paid': r['mean_months_paid'], 'mean_accumulated_unpaid': r['mean_accumulated_unpaid'], 'std_npv_per_share': r['std_npv_per_share'], 'npv_per_additional_btc': r['npv_per_additional_btc']} for r in btc_credit_sensitivity_results])
    plot_images['btc_credit_sensitivity_analysis'] = generate_btc_credit_sensitivity_plots(btc_credit_sensitivity_df, config_dict['baseline_btc_credit'], args.plots_dir)[1]

    # Save results to JSON
    logger.info("="*70)
    logger.info("SAVING RESULTS TO JSON")
    logger.info("="*70)

    # Convert results to dictionaries for JSON serialization
    baseline_dict = baseline_results.__dict__ if baseline_results else None
    scenario_list = [{name: row[name] for name in scenario_results.dtype.names} for row in scenario_results] if len(scenario_results) > 0 else []
    sensitivity_list = [{name: row[name] for name in sensitivity_results.dtype.names} for row in sensitivity_results] if len(sensitivity_results) > 0 else []
    dividend_rate_sensitivity_list = [{name: row[name] for name in dividend_rate_sensitivity_results.dtype.names} for row in dividend_rate_sensitivity_results] if len(dividend_rate_sensitivity_results) > 0 else []
    btc_credit_sensitivity_list = [{name: row[name] for name in btc_credit_sensitivity_results.dtype.names} for row in btc_credit_sensitivity_results] if len(btc_credit_sensitivity_results) > 0 else []

    results_data = {
        'metadata': {
            'timestamp': datetime.now().isoformat(),
            'version': '1.0'
        },
        'configuration': config_dict,
        'baseline_results': baseline_dict,
        'scenario_results': scenario_list,
        'sensitivity_results': sensitivity_list,
        'dividend_rate_sensitivity_results': dividend_rate_sensitivity_list,
        'btc_credit_sensitivity_results': btc_credit_sensitivity_list,
        'plot_images': plot_images
    }

    json_file = args.output.replace('.html', '.json')
    save_results_to_json(results_data, json_file)

    total_time = time.time() - start_time
    minutes, seconds = divmod(int(total_time), 60)

    print(f"\n{'='*70}\nANALYSIS COMPLETE\n{'='*70}")
    print(f"✓ Results saved to: {json_file}")
    print(f"✓ Plots saved to: {args.plots_dir}/")
    print(f"✓ To generate HTML report: python html_report_generator.py --input {json_file} --output {REPORTS_DIR / 'sata_valuation_report.html'}")
    print(f"✓ Total execution time: {minutes}:{total_time - minutes*60:05.2f}")


if __name__ == '__main__':
    main()

